using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("BCG-iContact")]
[assembly: AssemblyDescriptionAttribute("Contact Management Solution")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © BCG")]
[assembly: AssemblyCompanyAttribute("BCG")]
[assembly: AssemblyProductAttribute("iContact")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("00CE0EDF-D5C2-4CA9-98E8-B8770582A451")]

